# Generated by Django 4.1 on 2022-09-06 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_inertia', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='category',
            table='categories',
        ),
    ]
